services:
  app:
    build: .
    ports:
      - 3001:3001
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
    volumes:
      - ./documents:/app/documents
      - ./database:/app/database
    restart: always

